### ISSUE TITLE
Support for react native 0.81+

### ISSUE THREAD

**Issue by dmytrodernoviy** [plaid/react-native-plaid-link-sdk#803]
Issue: C++ compilation failure when building Android app with
  React Native 0.81.1 and react-native-plaid-link-sdk 12.4.0. The
  build fails during CMake compilation with overloaded virtual
  function errors in the generated JSI code.

  What I was trying to do: Build an Android debug APK using
  ./gradlew assembleDebug after upgrading React Native from 0.80.1
   to 0.81.1.

  What happened instead: The build fails at the C++ compilation
  step with errors indicating that the Plaid SDK's generated
  TurboModule methods conflict with the base TurboModule interface
   in React Native 0.81.1.

  Environment

  |                           |
     |
  |---------------------------|-----------------------------------
  ---|
  | Plaid Link React Native   | 12.4.0
     |
  | ReactNative Version       | 0.81.1
     |
  | Occurs on Android         | yes
     |
  | Android OS Version        | N/A (compilation error, not
  runtime) |
  | Android Devices/Emulators | N/A (compilation error, not
  runtime) |
  | Occurs on iOS             | Unknown (not tested)
     |
  | iOS Version               | N/A
     |
  | iOS Devices/Emulators     | N/A
     |
  | Link Session ID           | N/A (compilation error, not
  runtime) |

  Steps to Reproduce

  1. Create a React Native 0.81.1 project with New Architecture
  enabled (newArchEnabled=true)
  2. Install react-native-plaid-link-sdk@12.4.0
  3. Run cd android && ./gradlew assembleDebug
  4. Observe C++ compilation failure

  Configuration: Using New Architecture (Fabric/TurboModules) with
   newArchEnabled=true in gradle.properties.

  Expected Result

  The Android build should compile successfully without C++
  compilation errors.

  Logs

  FAILED: rnplaidlink_autolinked_build/CMakeFiles/react_codegen_rn
  plaidlink.dir/react/renderer/components/rnplaidlink/rnplaidlinkJ
  SI-generated.cpp.o

  C/C++: In file included from
  /Users/.../node_modules/react-native-plaid-link-sdk/android/buil
  d/generated/source/codegen/jni/react/renderer/components/rnplaid
  link/rnplaidlinkJSI-generated.cpp:10:
  C/C++: /Users/.../node_modules/react-native-plaid-link-sdk/andro
  id/build/generated/source/codegen/jni/react/renderer/components/
  rnplaidlink/rnplaidlinkJSI.h:23:16: error: 'facebook::react::Nat
  ivePlaidLinkModuleAndroidCxxSpecJSI::create' hides overloaded
  virtual function [-Werror,-Woverloaded-virtual]
  C/C++:    23 |   virtual void create(jsi::Runtime &rt,
  jsi::String token, bool noLoadingState, jsi::String logLevel) =
  0;
  C/C++:       |                ^
  C/C++: /Users/.../react-android-0.81.1-debug/prefab/modules/reac
  tnative/include/ReactCommon/TurboModule.h:125:22: note: hidden
  overloaded virtual function
  'facebook::react::TurboModule::create' declared here: different
  number of parameters (2 vs 4)
  C/C++:   125 |   virtual jsi::Value create(
  C/C++:       |                      ^
  C/C++: In file included from
  /Users/.../node_modules/react-native-plaid-link-sdk/android/buil
  d/generated/source/codegen/jni/react/renderer/components/rnplaid
  link/rnplaidlinkJSI-generated.cpp:10:
  C/C++: /Users/.../node_modules/react-native-plaid-link-sdk/andro
  id/build/generated/source/codegen/jni/react/renderer/components/
  rnplaidlink/rnplaidlinkJSI.h:131:16: error:
  'facebook::react::NativePlaidLinkModuleiOSCxxSpecJSI::create'
  hides overloaded virtual function [-Werror,-Woverloaded-virtual]
  C/C++:   131 |   virtual void create(jsi::Runtime &rt,
  jsi::String token, bool noLoadingState) = 0;
  C/C++:       |                ^
  C/C++: /Users/.../react-android-0.81.1-debug/prefab/modules/reac
  tnative/include/ReactCommon/TurboModule.h:125:22: note: hidden
  overloaded virtual function
  'facebook::react::TurboModule::create' declared here: different
  number of parameters (2 vs 3)
  C/C++:   125 |   virtual jsi::Value create(
  C/C++:       |                      ^
  C/C++: 2 errors generated.

  Root Cause: The generated TurboModule JSI code for Plaid SDK
  defines create methods with 3-4 parameters that hide the base
  TurboModule::create method (which has 2 parameters), causing
  compilation errors due to -Werror,-Woverloaded-virtual flag.

  Additional Context: This appears to be a compatibility issue
  between react-native-plaid-link-sdk 12.4.0 and React Native
  0.81.1's TurboModule interface changes. The issue did not occur
  with React Native 0.80.1.

**Comment by dmytrodernoviy** [comment]
@dtroupe-plaid  thx a lot, now it works as expected

**Comment by dmytrodernoviy** [comment]
@dtroupe-plaid seems like Android is fixed now, but iOS fails after launch with following error:

com.facebook.react.runtime.JavaScript (12): "*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[5]"

I tried to temporary remove the plaid package, cause i think that the problem may be in another package, but no. After removing app works correctly.

**Comment by jwoodmansey** [comment]
> [@dtroupe-plaid](https://github.com/dtroupe-plaid) seems like Android is fixed now, but iOS fails after launch with following error:
> 
> com.facebook.react.runtime.JavaScript (12): "*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[5]"
> 
> I thought that problem may be in some another package, so I tried to temporary remove the plaid package. After removing app works correctly.

Yes I am seeing the same, Android is now fixed but a runtime crash on iOS. Spent this morning trying to track it down as it wasn't obvious which package was causing it, it looked like RNSafeAreaProvider but it was just a red-herring in the stack trace. 

So the current status of this package in relation to 0.81.1 is:
Android requires the CMake fix included in 12.5.1, but iOS breaks in this version and requires version 12.5.0. 

This is the last package blocking us upgrading to 0.81.1 so I will try dig deeper and patch if I can. 🙏
